environment:
  matrix:
    - GENERATOR : "Visual Studio 14 2015 Win64"
      QTDIR: C:\Qt\5.7\msvc2015_64
      PLATFORM: x64

configuration:
  - Release

branches:
  only:
    - master

before_build:
  - set PATH=%QTDIR%\bin;%PATH%
  - qmake
  
build_script:
  - nmake

