
language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev 
  - sudo apt-get install qt5-default qttools5-dev-tools
  - sudo apt-get install libprotobuf-dev

script:
  - qmake -project
  - qmake quickqanava2.pro
  - make

  