site_name: 'QuickQanava C++11/Qt/QML graph drawing library'
site_url: 'http://www.destrat.io/quickqanava'
site_author: 'cneben'
pages:
  - 'Home': 'index.md'
  - 'Installation': 'installation.md'
  - 'Getting started': 'gettingstarted.md'
  - 'Samples': 'samples.md'
  - 'Utilities': 'utilities.md'
  - 'API Reference': 'reference.md'
  - 'Licence': 'licence.md'

theme: 'material'

repo_name: 'GitHub'
repo_url: 'https://github.com/cneben/QuickQanava'

copyright: 'Copyright (c) 2016 Delia Stratégie'

#extra_css: ['extra.css']
 
extra:
  version: '0.6'
  logo: 'images/logo-footer.png'
  palette:
    primary: 'cyan'
    accent: 'orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    github: 'cneben'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition