site_name: 'QuickQanava graph visualization library'
site_url: 'http://www.destrat.io/quickqanava'
site_author: 'cneben'
use_directory_urls: false
pages:
  - 'QuickQanava': 'index.md'
  - 'Installation': 'installation.md'
  - 'Topology': 'topology.md'
  - 'Styles': 'styles.md'
  - 'Utilities': 'utilities.md'
  - 'Advanced use': 'advanced.md'
  - 'Samples': 'samples.md'
  - 'API Reference': 'reference.md'
  - 'Licence': 'licence.md'

theme: 'material'

repo_name: 'GitHub'
repo_url: 'https://github.com/cneben/QuickQanava'

copyright: 'Copyright &copy; 2017 Delia Stratégie'

#extra_css: ['extra.css']
 
extra:
  version: '0.8'
  logo: 'images/logo.png'
  palette:
    primary: 'indigo'
    accent: 'amber'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    github: 'cneben'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/QuickQanava'
    - type: 'github'
      link: 'https://github.com/cneben'

markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - footnotes
  - meta
  - toc(permalink=true)
  
  